Bank/Bank/ViewModels/TransactionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.ViewModels
{
    public class TransactionViewModel
    {
        [Required(ErrorMessage = "Transaction account must be specified")]        
        public int FromAccountId { get; set; }
        public decimal OldAccountBalance { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Transaction date must be specified")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "Type must be specified")]
        [MaxLength(50)]
        public string Type { get; set; }

        [Required(ErrorMessage = "Operation must be specified")]
        [MaxLength(50)]
        public string Operation { get; set; }

        [Required(ErrorMessage = "Amount must be specified")]
        [Range(0, int.MaxValue)]        
        public decimal Amount { get; set; }

        [Required(ErrorMessage = "The balance cannot go under 0.")]
        [Range(0, int.MaxValue, ErrorMessage = "The amount cannot be negative.")]
        public decimal Balance { get; set; }
        [MaxLength(50)]
        public string Symbol { get; set; }
        [MaxLength(50)]
        public string Bank { get; set; }
        [MaxLength(50)]
        public string ToAccount { get; set; }
        
        public IQueryable<SelectListItem> Types { get; set; }
        public IQueryable<SelectListItem> Operations { get; set; }
        public IQueryable<SelectListItem> Symbols { get; set; }
        public ErrorMessageViewModel ErrorMessageViewModel { get; set; }
    }    
}

Bank/Bank/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bank.Data;
using Bank.Interfaces;
using Bank.Models;
using Bank.Services;
using Bank.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Bank.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext dbContext;
        private readonly IAccountsRepository _accountsRepository;
        private readonly ICustomersRepository _customersRepository;
        private readonly IDispositionsRepository _dispositionsRepository;
        private readonly ITransactionsRepository _transactionsRepository;
        private readonly CustomerSearchService _customerSearchService;
        private readonly AccountServices _accountServices;
        private readonly ViewModelsService _viewmodelsServices;
        private readonly TransactionServices _transactionServices;

        public TransactionController(ILogger<HomeController> logger, ApplicationDbContext dbContext, IAccountsRepository accountRepository,
            ICustomersRepository customersRepository, IDispositionsRepository dispositionsRepository, ITransactionsRepository transactionsRepository, CustomerSearchService searchService, AccountServices accountServices, ViewModelsService viewmodelsServices, TransactionServices transactionServices)
        {
            _logger = logger;
            this.dbContext = dbContext;
            _accountsRepository = accountRepository;
            _customersRepository = customersRepository;
            _dispositionsRepository = dispositionsRepository;
            _transactionsRepository = transactionsRepository;
            _customerSearchService = searchService;
            _accountServices = accountServices;
            _viewmodelsServices = viewmodelsServices;
            _transactionServices = transactionServices;
        }

        public IActionResult TransferThisBank(int id)
        {
            var model = _viewmodelsServices.CreateTransferThisBankTransactionViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult TransferThisBank(TransferThisBankTransactionViewModel model)
        {
            bool ok = true;           

            if (!ModelState.IsValid || !ok)
            {
                ModelState.AddModelError(string.Empty, "Please fill in all the required fields.");

                var newModel = _viewmodelsServices.CreateTransferThisBankTransactionViewModel(model.FromAccountId);

                return View(newModel);
            }

            //This validation was originally in CheckTransferThisBankModelIsOkAndReturnViewmodel with the others, but because of unittesting-error I moved it here
            if (!_transactionServices.ToAccountExistInThisBank(model.ToAccountId))
            {
                model.ErrorMessageViewModel = new ErrorMessageViewModel()
                {
                    ErrorMessage = "No such account exists. Enter the Account ID you want to transfer to."
                };

                return View(model);
            }

            model = _transactionServices.CheckTransferThisBankModelIsOkAndReturnViewmodel(model);

            if (model.ErrorMessageViewModel.ErrorMessage != "")
            {                         
                return View(model);
            }

            _transactionServices.CreateTransferThisBankFromAccountTransaction(model);
            _transactionServices.CreateTransferThisBankToAccountTransaction(model);
                             
            return View("SuccessConfirmation");                          
        }

        public IActionResult TransferOtherBank(int id)
        {
            var model = _viewmodelsServices.CreateTransferViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult TransferOtherBank(TransferTransactionViewModel model)
        {
            bool ok = true;

            if (!ModelState.IsValid || !ok)
            {
                ModelState.AddModelError(string.Empty, "Please fill in all the required fields.");

                var newModel = _viewmodelsServices.CreateTransferViewModel(model.FromAccountId);

                return View(newModel);
            }

            model = _transactionServices.CheckTransferOtherBankModelIsOkAndReturnViewmodel(model);

            if (model.ErrorMessageViewModel.ErrorMessage != "")
            {
                return View(model);
            }

            _transactionServices.CreateTransferToOtherBankTransaction(model);                           

            return View("SuccessConfirmation");

        }

        public IActionResult Withdrawal(int id)
        {
            var model = _viewmodelsServices.CreateWithdrawalViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Withdrawal(AddTransactionViewModel model)
        {
            bool ok = true;

            if (!ModelState.IsValid || !ok)
            {
                ModelState.AddModelError(string.Empty, "Please fill in all the required fields.");

                var newModel = _viewmodelsServices.CreateWithdrawalViewModel(model.FromAccountId);

                return View(newModel);
            }

            model = _transactionServices.CheckWithdrawalTransactionModelIsOkAndReturnViewmodel(model);

            if (model.ErrorMessageViewModel.ErrorMessage != "")
            {
                return View(model);
            }

            _transactionServices.CreateWithdrawalTransaction(model);            

            return View("SuccessConfirmation");
            
        }
        public IActionResult Deposit(int id)
        {
            var model = _viewmodelsServices.CreateDepositViewModel(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Deposit(AddTransactionViewModel model)
        {
            bool ok = true;

            if (!ModelState.IsValid || !ok)
            {
                ModelState.AddModelError(string.Empty, "Please fill in all the required fields.");

                var newModel = _viewmodelsServices.CreateDepositViewModel(model.FromAccountId);

                return View(newModel);
            }

            model = _transactionServices.CheckDepositTransactionModelIsOkAndReturnViewmodel(model);

            if (model.ErrorMessageViewModel.ErrorMessage != "")
            {
                return View(model);
            }

            _transactionServices.CreateDepositTransaction(model);                     

            return View("SuccessConfirmation");                      
        }

       
    }
}

Bank/Bank/Views/Transaction/Deposit.cshtml
@model AddTransactionViewModel


<section class="generic-banner relative">
    <div class="container">
        <div class="row height align-items-center justify-content-center">
            <div class="col-lg-10">
                <div class="generic-banner-content">
                    <!-- Start service Area -->

                    <div class="row justify-content-center align-items-center flex-column pb-30">
                        <h1 class="text-white">Create Transaction</h1>                        
                        <p class="text-white">Fill in the fields below to create a new Deposit Transaction</p>
                    </div>

                    <button class="genric-btn default circle text-uppercase mb-30"><a style="color:black;" asp-action="ShowAccount" asp-controller="Account" asp-route-id="@Model.FromAccountId">Back to Account</a></button>

                </div>
            </div>
        </div>
    </div>
</section>

<div class="main-wrapper">
    <!-- Start service Area -->
    <section class="service-area pt-100" id="feature">
        <div class="container">

            <div class="row justify-content-center align-items-start">               

                <form asp-action="Deposit" asp-controller="Transaction" method="post">
                    <input asp-for="@Model.FromAccountId" value="@Model.FromAccountId" type="hidden" />
                    <input asp-for="@Model.OldAccountBalance" value="@Model.OldAccountBalance" type="hidden" />
                    <input asp-for="@Model.Operation" value="@Model.Operation" type="hidden" />
                    <input asp-for="@Model.Type" value="@Model.Type" type="hidden" />

                    <div class="row">
                        <div class="col-lg-12 cols ">
                            <h4>Make a Cash Deposit</h4>
                            <br/>
                        </div>
                    </div>

                        <div class="row">                           

                            <div class="col-lg-6 cols">
                                <label for="FromAccountId">Account</label>
                                <input type="text" class="form-control" id="FromAccountId" asp-for="@Model.FromAccountId" value="@Model.FromAccountId" placeholder="@Model.FromAccountId" disabled />
                                @*<span style="color: red" asp-validation-for="@Model.FromAccountId"></span>*@
                            </div>


                            <div class="col-lg-6 cols">
                                <label for="OldAccountBalance">Account Balance</label>
                                <input type="text" class="form-control" id="OldAccountBalance" asp-for="@Model.OldAccountBalance" value="@Model.OldAccountBalance" placeholder="@Model.OldAccountBalance" disabled />
                                @*<span style="color: red" asp-validation-for="@Model.OldAccountBalance"></span>*@
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12 cols">
                                <label for="Date">Date</label>
                                <input class="form-control" id="Date" asp-for="@Model.Date" type="date" placeholder="Date" min="@Model.Date" />
                                <span style="color:red" asp-validation-for="@Model.Date"></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-8 cols">
                                <label for="Amount">Amount</label>
                                <input class="form-control" id="Amount" asp-for="@Model.Amount" placeholder="Amount" />
                                <span style="color:red" asp-validation-for="@Model.Amount"></span>
                            </div>
                            <div class="col-lg-4 cols">
                                <label for="Type">Type</label>
                                <input class="form-control" id="Type" asp-for="@Model.Type" placeholder="@Model.Type" disabled />
                                <span style="color:red" asp-validation-for="@Model.Type"></span>
                            </div>                           
                        </div>
                        <div class="row">
                            <div class="col-lg-12 cols">
                                <label for="Operation">Operation</label>
                                <input class="form-control" id="Operation" asp-for="@Model.Operation" placeholder="@Model.Operation" disabled />
                                <span style="color:red" asp-validation-for="@Model.Operation"></span>
                            </div>

                            <div class="col-lg-12 cols">
                                <label for="Symbol">Description</label>
                                <input asp-for="@Model.Symbol" type="text" class="form-control" id="Symbol" placeholder="Write a description...">
                                <span style="color:red" asp-validation-for="@Model.Symbol"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 cols">
                                <label for="Bank">To Bank</label>
                                <input asp-for="@Model.Bank" type="text" class="form-control" id="Bank" disabled>
                                <span style="color:red" asp-validation-for="@Model.Bank"></span>
                            </div>

                            <div class="col-lg-6 cols">
                                <label for="ToAccount">To Account</label>
                                <input asp-for="@Model.ToAccount" type="text" class="form-control" id="ToAccount" disabled>
                                <span style="color:red" asp-validation-for="@Model.ToAccount"></span>
                            </div>
                        </div>
                        <br />

                        <div class="row justify-content-center align-items-start">
                            <button type="submit" asp-controller="Transaction" asp-action="Deposit" class="primary-btn default circle text-uppercase mb-30">Create Transaction</button>
                        </div>
                        <br />
                        <div class="row justify-content-center align-items-start">
                            <h4 style="color:red;">@Html.ValidationSummary(false, "")</h4>
                        </div>

                </form>
            </div>

            @Html.Partial("_TransactionError", Model.ErrorMessageViewModel)
            <br />
        </div>
    </section>
</div>

Bank/Bank/Views/Transaction/SuccessConfirmation.cshtml
<!-- Start banner Area -->
<section class="generic-banner relative">
    <div class="container">
        <div class="row height align-items-center justify-content-center">
            <div class="col-lg-10">
                <div class="generic-banner-content">

                    <h1 class="text-white">Success!</h1>

                    <p class="text-white">The transaction has been created.</p>                    

                </div>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->

Bank/Bank/Views/Transaction/TransferOtherBank.cshtml
@model TransferTransactionViewModel


<section class="generic-banner relative">
    <div class="container">
        <div class="row height align-items-center justify-content-center">
            <div class="col-lg-10">
                <div class="generic-banner-content">
                    <!-- Start service Area -->

                    <div class="row justify-content-center align-items-center flex-column pb-30">
                        <h1 class="text-white">Create Transaction</h1>
                        <p class="text-white">Fill in the fields below to make a transfer to a bank account at a different bank</p>
                    </div>

                    <button class="genric-btn default circle text-uppercase mb-30"><a style="color:black;" asp-action="ShowAccount" asp-controller="Account" asp-route-id="@Model.FromAccountId">Back to Account</a></button>

                </div>
            </div>
        </div>
    </div>
</section>

<div class="main-wrapper">
    <!-- Start service Area -->
    <section class="service-area pt-100" id="feature">
        <div class="container">

            <div class="row justify-content-center align-items-start">

                <form asp-action="TransferOtherBank" asp-controller="Transaction" method="post">
                    <input asp-for="@Model.FromAccountId" type="hidden" />
                    <input asp-for="@Model.OldAccountBalance" type="hidden" />
                    <input asp-for="@Model.Operation" type="hidden" />
                    <input asp-for="@Model.Type" type="hidden" />

                    <div class="row">
                        <div class="col-lg-12 cols ">
                            <h4>Make a Transfer</h4>
                            <br />
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-lg-6 cols">
                            <label for="FromAccountId">Account</label>
                            <input type="text" class="form-control" id="FromAccountId" asp-for="@Model.FromAccountId" value="@Model.FromAccountId" placeholder="@Model.FromAccountId" disabled />
                            @*<span style="color: red" asp-validation-for="@Model.FromAccountId"></span>*@
                        </div>


                        <div class="col-lg-6 cols">
                            <label for="OldAccountBalance">Account Balance</label>
                            <input type="text" class="form-control" id="OldAccountBalance" asp-for="@Model.OldAccountBalance" value="@Model.OldAccountBalance" placeholder="@Model.OldAccountBalance" disabled />
                            @*<span style="color: red" asp-validation-for="@Model.OldAccountBalance"></span>*@
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 cols">
                            <label for="Date">Date</label>
                            <input class="form-control" id="Date" asp-for="@Model.Date" type="date" placeholder="Date" min="@Model.Date" />
                            <span style="color:red" asp-validation-for="@Model.Date"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-8 cols">
                            <label for="Amount">Amount</label>
                            <input class="form-control" id="Amount" asp-for="@Model.Amount" placeholder="Amount" />
                            <span style="color:red" asp-validation-for="@Model.Amount"></span>
                        </div>
                        <div class="col-lg-4 cols">
                            <label for="Type">Type</label>
                            <input class="form-control" id="Type" asp-for="@Model.Type" placeholder="@Model.Type" disabled />
                            <span style="color:red" asp-validation-for="@Model.Type"></span>
                        </div>

                    </div>
                    <div class="row">
                        
                        <div class="col-lg-12 cols">
                            <label for="Operation">Operation</label>
                            <input class="form-control" id="Operation" asp-for="@Model.Operation" placeholder="@Model.Operation" disabled />
                            <span style="color:red" asp-validation-for="@Model.Operation"></span>
                        </div>

                        <div class="col-lg-12 cols">
                            <label for="Symbol">Description</label>
                            <input asp-for="@Model.Symbol" type="text" class="form-control" id="Symbol" placeholder="Write a description...">
                            <span style="color:red" asp-validation-for="@Model.Symbol"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 cols">
                            <label for="Bank">To Bank</label>
                            <input asp-for="@Model.Bank" type="text" class="form-control" id="Bank">
                            <span style="color:red" asp-validation-for="@Model.Bank"></span>
                        </div>

                        <div class="col-lg-6 cols">
                            <label for="ToAccount">To Account</label>
                            <input asp-for="@Model.ToAccount" type="text" class="form-control" id="ToAccount">
                            <span style="color:red" asp-validation-for="@Model.ToAccount"></span>
                        </div>
                    </div>
                    <br />

                    <div class="row justify-content-center align-items-start">
                        <button type="submit" asp-controller="Transaction" asp-action="TransferOtherBank" class="primary-btn default circle text-uppercase mb-30">Create Transaction</button>
                    </div>
                    <br />
                    <div class="row justify-content-center align-items-start">
                        <h4 style="color:red;">@Html.ValidationSummary(false, "")</h4>
                    </div>

                </form>
            </div>

            @Html.Partial("_TransactionError", Model.ErrorMessageViewModel)
            <br />
        </div>
    </section>
</div>

Bank/Bank/Views/Transaction/TransferThisBank.cshtml
@model TransferThisBankTransactionViewModel


<section class="generic-banner relative">
    <div class="container">
        <div class="row height align-items-center justify-content-center">
            <div class="col-lg-10">
                <div class="generic-banner-content">
                    <!-- Start service Area -->

                    <div class="row justify-content-center align-items-center flex-column pb-30">
                        <h1 class="text-white">Create Transaction</h1>
                        <p class="text-white">Fill in the fields below to make a transfer to another bank account in this bank</p>
                    </div>

                    <button class="genric-btn default circle text-uppercase mb-30"><a style="color:black;" asp-action="ShowAccount" asp-controller="Account" asp-route-id="@Model.FromAccountId">Back to Account</a></button>

                </div>
            </div>
        </div>
    </div>
</section>

<div class="main-wrapper">
    <!-- Start service Area -->
    <section class="service-area pt-100" id="feature">
        <div class="container">

            <div class="row justify-content-center align-items-start">

                <form asp-action="TransferThisBank" asp-controller="Transaction" method="post">
                    <input asp-for="@Model.FromAccountId" type="hidden" />
                    <input asp-for="@Model.OldAccountBalance" type="hidden" />
                    <input asp-for="@Model.Operation" type="hidden" />
                    <input asp-for="@Model.Type" type="hidden" />
                    <input asp-for="@Model.Bank" type="hidden" />

                    <div class="row">
                        <div class="col-lg-12 cols ">
                            <h4>Make a Transfer</h4>
                            <br />
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-lg-6 cols">
                            <label for="FromAccountId">Account</label>
                            <input type="text" class="form-control" id="FromAccountId" asp-for="@Model.FromAccountId" value="@Model.FromAccountId" placeholder="@Model.FromAccountId" disabled />
                            @*<span style="color: red" asp-validation-for="@Model.FromAccountId"></span>*@
                        </div>


                        <div class="col-lg-6 cols">
                            <label for="OldAccountBalance">Account Balance</label>
                            <input type="text" class="form-control" id="OldAccountBalance" asp-for="@Model.OldAccountBalance" value="@Model.OldAccountBalance" placeholder="@Model.OldAccountBalance" disabled />
                            @*<span style="color: red" asp-validation-for="@Model.OldAccountBalance"></span>*@
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-12 cols">
                            <label for="Date">Date</label>
                            <input class="form-control" id="Date" asp-for="@Model.Date" type="date" placeholder="Date" min="@Model.Date" />
                            <span style="color:red" asp-validation-for="@Model.Date"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-8 cols">
                            <label for="Amount">Amount</label>
                            <input class="form-control" id="Amount" asp-for="@Model.Amount" placeholder="Amount" />
                            <span style="color:red" asp-validation-for="@Model.Amount"></span>
                        </div>
                        <div class="col-lg-4 cols">
                            <label for="Type">Type</label>
                            <input class="form-control" id="Type" asp-for="@Model.Type" placeholder="@Model.Type" disabled />
                            <span style="color:red" asp-validation-for="@Model.Type"></span>
                        </div>

                    </div>
                    <div class="row">

                        <div class="col-lg-12 cols">
                            <label for="Operation">Operation</label>
                            <input class="form-control" id="Operation" asp-for="@Model.Operation" placeholder="@Model.Operation" disabled />
                            <span style="color:red" asp-validation-for="@Model.Operation"></span>
                        </div>

                        <div class="col-lg-12 cols">
                            <label for="Symbol">Description</label>
                            <input asp-for="@Model.Symbol" type="text" class="form-control" id="Symbol" placeholder="Write a description...">
                            <span style="color:red" asp-validation-for="@Model.Symbol"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 cols">
                            <label for="Bank">To Bank</label>
                            <input asp-for="@Model.Bank" type="number" class="form-control" id="Bank" value="This Bank" placeholder="Bitcoin Bank" disabled>
                            <span style="color:red" asp-validation-for="@Model.Bank"></span>
                        </div>

                        <div class="col-lg-6 cols">
                            <label for="ToAccount">To Account</label>
                            <input asp-for="@Model.ToAccountId" type="number" class="form-control" id="ToAccount" placeholder="Account ID">
                            <span style="color:red" asp-validation-for="@Model.ToAccountId"></span>
                        </div>
                    </div>
                    <br />

                    <div class="row justify-content-center align-items-start">
                        <button type="submit" asp-controller="Transaction" asp-action="TransferThisBank" class="primary-btn default circle text-uppercase mb-30">Create Transaction</button>
                    </div>
                    <br />
                    <div class="row justify-content-center align-items-start">
                        <h4 style="color:red;">@Html.ValidationSummary(false, "")</h4>
                    </div>

                </form>
            </div>

            @Html.Partial("_TransactionError", Model.ErrorMessageViewModel)
            <br />
        </div>
    </section>
</div>